export default [
  {
    name: "Avatar",
    textChunks: [
      "The main character of the movie Avatar is Jake Sully, who is working for a human mining company on Pandora, a moon with an extremely valuable resource called unobtanium, along with a native people called the Na'vi. Jake's job is to control a Na'vi body replica, called an Avatar, and to join the Na'vi society and learn about them, so the mining company can invade their land and mine the valuable area one of their tribes rests on. However, after he meets Neytiri, one of the Na’vi, he starts to integrate with the tribe. As he watches the mining company destroy the Na'vi people's home, he realizes that it is the humans that need to leave, and not the natives. Realizing this, he proceeds to gather all the Na'vi and the animals of the world and drive out the humans.",

      "Stories like Avatar help highlight the importance of going beyond what society expects us to do and doing what we think is right for us and the people around us. In Avatar, although Jake has been ordered to always work for the humans and just scout out the Na’vi, and he has been promised a high reward for doing so, he still chooses to side with the Na’vi and fight back against his own people, the humans. He does this because he knows that what the humans are doing is wrong, so instead of doing what his society tells him to do, Jake does what he knows is best for him, his new people, and their world. Through Jake’s choice to fight with the Na’vi, Cameron offers all viewers an insight into how we should choose our own individual actions—rather than deciding what we do based on societal views, we should do what we know is best for us and those around us.",
    ],
  },
  {
    name: "By the Waters of Babylon",
    textChunks: [
      `"By the Waters of Babylon," a short story by Stephen Vincent Benét, follows a boy in a post-apocalyptic world who ventures out of his simple and very spiritual life to find the "City of the Gods," which we know today as New York City. After getting approval from his father, a priest, to go on the journey, he goes across the Hudson River and into the city, which is further than anyone in his community has gone for generations. There, he explores the city and finds all the incredible technological feats that the "gods" had created. After that, he goes up to a building and finds the corpse of a dead man who died looking out at the city he knew and loved. When John sees the humane facial expression, he realizes that the "gods" that once inhabited the city were actually just men like him, and that they were the ones that created and destroyed the city he is now exploring.`,
      `Through John’s choice to explore the city instead of keeping far away from it, as his society expects, Benét shows the importance of choosing your actions based on your own thoughts and ideas, and not the ideas of others in the society. Although others in John’s community, including his own father, believe that going to the “city of the gods” will get him killed, John knows that he should instead follow his heart and go anyway, which ultimately results in him bringing back new historical knowledge to his people. Because of these choices, he discovers the true nature of the city, and also what preceded his society, resulting in him pushing past the boundaries of his culture which ultimately benefits both him and his community.`,
    ],
  },
  {
    name: "Ellen Foster",
    textChunks: [
      "Ellen Foster, a book by Kaye Gibbons, is about a white girl named Ellen, living in the deep South, who must journey from family to family in order to find a home where she can live in peace and be loved. The story starts when she runs away from her constantly drunk and cruel father who has just killed her mother. As she begins this journey, she holds a prejudice, common among the other white characters in the narrative, against African-Americans, viewing them as inferior and unclean, even though she has a close friendship with a black girl named Stella. As Ellen continues, she stays friends with Stella, and stays over her house, even though she was told as a child not to sleep in the houses of African-Americans. As Stella helps Ellen along in her journey, Ellen comes to realize that black people are equal to, and oftentimes far more moral, than the white people in her life, and certainly not inferior. At the end, she finds a permanent home in the house of an African-American mother who takes in orphans, and Ellen finally finds a place where she is loved and cared for, and where she has enough to live a good life.",
      "The irony of Ellen choosing to live in a home that she once would not even have spent a night in, and choosing someone she once thought of as inferior to be her mom, helps illustrate a major theme that you should always try to use your own views and intuition instead of accepting common societal stereotypes when judging someone. Stories like Ellen Foster that involve important individual decisions help readers understand the value of making choices based on what you know and what is good for you and those around you. Although many people in Ellen’s life were racist, and Ellen would not have even slept in an African-American house at the start of her journey, she makes the decision to live in her final home because she knows it is the best family for her. Rather than basing her decision about where to find a home using her culture’s views of race, she looks for what she knows is important in a parent—a person’s character and kindness—and ends up with a fantastic parent, and becomes a valued member of her new family. Through Ellen’s decision, Gibbons is emphasizing the theme that all people should base their actions on what they know is best for them and others around them, rather than preexisting cultural knowledge or stereotypes.",
    ],
  },
  {
    name: "Romeo and Juliet",
    textChunks: [
      `Romeo and Juliet, a play by William Shakespeare that takes place in 15th-century Italy, is about two teenagers from rival families who fall deeply in love with each other. When they meet each other at a party, it’s love at first sight, and shortly afterward, their local friar, Friar Lawrence, marries them. However, after yet another fight between the families breaks out and Romeo is banished, Juliet's father decides to marry her to Paris, another aristocrat in their city of Verona. After receiving advice from Friar Lawrence, Juliet takes a potion that makes her appear to be dead, which turns the planned wedding into a funeral. Hearing of Juliet's "death," Romeo rushes back to Verona, and seeing her lying on the tomb, he kills himself. When Juliet wakes up, she sees Romeo is dead, and kills herself, too.`,
      `Romeo and Juliet allows readers to grasp the importance of determining your own important decisions instead of letting others determine your fate for you. Until the very end of the play, almost every Montague and Capulet hates everyone in the opposing family, but Romeo and Juliet, rather than adhering to this cultural norm, decide to pursue their love and be together. They continue to decide their own fate all the way to the point where they choose to kill themselves rather than let their families’ rivalry determine their lives. By utilizing Romeo and Juliet’s insistence on choosing their own life paths based on what they want and what is right for them, Shakespeare shows how all viewers should also consider basing their decisions on what is best for themselves and others around them instead of succumbing to what society expects of them.`,
    ],
  },
  {
    name: "The Hobbit",
    textChunks: [
      "The Hobbit, a book by J.R.R. Tolkien, follows a hobbit named Bilbo Baggins on his journey across Middle Earth to reclaim treasure in a mountain stolen by a dragon. At first, because hobbits don't like to go out of their comfort zones, Bilbo pushes back against going on this adventure. However, after his friend Gandalf urges him to go, Bilbo chooses to embark on this journey that will change his life. With Gandalf and the other dwarfs that accompany him on his trip (all in hopes of acquiring the treasure), Bilbo expands his willingness to do new and hard things and acquires true leadership skills. Eventually, after many challenges, Bilbo and the team successfully obtain the treasure and bring it back.",
      "The Hobbit and other similar stories provide a guide for how all readers should approach their decision-making—by making choices that are based on what is good for themselves and others around them. When Bilbo is initially invited on the journey, he is frowned upon by the other hobbits for doing something difficult, because it is unusual in hobbit society to even consider leaving home. However, he decides to continue anyway, because he knows he might be a help to the rest of the team and it will also help him grow and stretch as an individual. Through Bilbo’s significant growth on this journey, as well as the monetary reward at the end, Tolkien shows the importance for all readers of making choices based on your own perspective and opinion, rather than what others believe is right or what they want you to do.",
    ],
  },
  {
    name: "Adventures of Huckleberry Finn",
    textChunks: [
      "Adventures of Huckleberry Finn, a novel by Mark Twain set in the pre-Civil War South, is about a boy named Huck Finn who escapes his abusive and always-drunk father and floats down the Mississippi River until he reaches a nearby island in the middle of the river. Here, he encounters Jim, a local slave who has escaped. The two join together, find a raft, and continue down the river through several states. Through multiple adventures and close calls with swindlers, Huck and Jim grow closer, and Huck struggles with his conscience. He's been taught that slaves are always property and the right thing to do would be to return Jim to his owner, but Huck can't bring himself to do it. He truly believes he will ultimately be sent to hell for not turning Jim in, but in the end, he decides he'd rather go to hell than see Jim return to slavery.",
      " Adventures of Huckleberry Finn and other stories like it that involve deep and significant decisions attempt to help the reader understand the importance of making decisions that benefit yourself and others, rather than what society tells you to do. Throughout the story, Huck has an inner mental battle over whether or not he should turn Jim in as an escaped slave, but in the end, he doesn’t do it—instead, he ends up helping Jim re-escape from confinement, even though others had told him this was very wrong. Instead of doing what everyone else in the deep South told him was right and wanted him to do, he did what he knew was right and best for everyone—going against the law and rescuing Jim. Through Huck, Mark Twain provides an example for how we should make our own important choices—based on what we know is right and good for us and those around us, rather than based on society’s views.",
    ],
  },
];
